### ISSUE TITLE
incomplete commit

### ISSUE THREAD

**Issue by mihai-satmarean** [bbelgodere/Vagrant-Ansible-Mesos#1]
Hi, while trying it out, because it looks like a nice project, but seems incomplete including:

Undefined variables.
fatal: [master2] => One or more undefined variables: 'zookeeper_url' is undefined
fatal: [master1] => One or more undefined variables: 'zookeeper_url' is undefined
fatal: [master3] => One or more undefined variables: 'zookeeper_url' is undefined

typos: in Vagrant definition file names of hosts cannot start with "-" eg "-slave1"

Hint:
The hosts file is not needed if you use 
a plugin
  # manage /etc/hosts on boxes and host
  # ( requires vagrant-hostmanager plugin)
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.include_offline = true 

Thank you!

**Comment by bbelgodere** [comment]
In an effort to make the ansible playbook more dynamic (relying on the vagrant generated inventory file for the groups and hostnames) I ended up breaking the end to end process. Will have it fixed next week. 

-BB

**Comment by bbelgodere** [comment]
All deployment issues fixed and verified. Go ahead and give it another shot.

**Comment by mihai-satmarean** [comment]
Great!
I did tryied it again, and yes the build process works now to the point
that all machines are up and running - awesome!.
The issue  I've seen but did not had time to debug was that the slaves
would not register and the master would change every some minutes without a
real need.

2015-01-08 4:04 GMT+01:00 Brian Belgodere notifications@github.com:

**Comment by bbelgodere** [comment]
I had those issue initially, but I modified the master VM range from 192.0.3.1-3 to 192.0.3.11-12 to avoid the vagrant warning regarding routers and _._.*.1, vagrant destroy, rebooted my hostmachine, and vagrant up and it seemed to work. Make sure you have pulled the latest ansible playbooks, I caught a typo in the mesosslave task where I was installing docker and it should have been docker.io, which cause the mesosslave service fail to start because of the /etc/mesos-slave/containerizers setting of 'docker/mesos'
